{
 "title": "00 - Streams - Overview",
 "tags": [ "streams" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"streams\"}, cluster_id)"
    }
   },
   {
    "name": "application",
    "label": "application",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"streams\", cluster_id=\"${cluster}\"}, application_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Topology",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_processor_node_metrics_process_rate{cluster_type=\"streams\", cluster_id=~\"${cluster}\", application_id=~\"${application}\", partition_id=~\"[0-9]+\", processor_node_id=~\".+\", task_id=~\".+\", thread_id=~\".+\"} "
    }
   ]
  },
  {
   "title": "Thread Allocation",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "\nsum without(task_id, partition_id) (kafka_streams_stream_task_metrics_process_rate{cluster_type=\"streams\", cluster_id=~\"$cluster\",  application_id=~\"${application}\", instance=~\".*\", thread_id=~\".*\", task_id=~\".*\", partition_id=~\".*\"})\n\n"
    }
   ]
  },
  {
   "title": "Task Allocation",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "\nkafka_streams_stream_task_metrics_process_rate{cluster_type=\"streams\", cluster_id=~\"$cluster\",  application_id=~\"${application}\",instance=~\".*\", thread_id=~\".*\", task_id=~\".*\", partition_id=~\"[0-9]+\"}\n\n"
    }
   ]
  },
  {
   "title": "Task Allocation (Matrix)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "\nkafka_streams_stream_task_metrics_process_rate{cluster_type=\"streams\", cluster_id=~\"$cluster\",  application_id=~\"${application}\", instance=~\".*\", thread_id=~\".*\", task_id=~\".*\", partition_id=~\"[0-9]+\"}\n\n"
    }
   ]
  }
 ]
}