{
 "title": "Kafka - Request Metrics",
 "tags": [
  "kafka_cluster",
  "kafka"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Time / Broker - Producer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "(kafka_network_requestmetrics_99thpercentile{name=\"TotalTimeMs\",request=\"Produce\",})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Time - Producer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "avg by(name) (kafka_network_requestmetrics_99thpercentile{request=\"Produce\", name =~ \".+Ms\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Time / Broker - Consumer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "(kafka_network_requestmetrics_99thpercentile{name=\"TotalTimeMs\",request=\"FetchConsumer\",})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Time - Consumer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "avg by (name) (kafka_network_requestmetrics_99thpercentile{request=\"FetchConsumer\", name =~ \".+Ms\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Time / Broker - Follower",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "(kafka_network_requestmetrics_99thpercentile{name=\"TotalTimeMs\",request=\"FetchFollower\",})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Time - Follower",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "avg by (name) (kafka_network_requestmetrics_99thpercentile{request=\"FetchFollower\", name =~ \".+Ms\"})",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}