{
 "title": "Kafka Cluster - Connections",
 "description": "Apache Kafka resource usage and throughput",
 "tags": [
  "kafka_cluster",
  "kafka"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "kafka_server_app_info_commitid" } }
  ]
 },
 "panels": [
  {
   "title": "Connection Count / Listener",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_socket_server_metrics_connection_count{job=\"kafka\", instance=~\"$instance\"}) by (listener)",
     "legendFormat": "{{listener}}"
    }
   ]
  },
  {
   "title": "Connection Rate / Listener",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_socket_server_metrics_connection_creation_rate{job=\"kafka\", instance=~\"$instance\"}) by (listener)",
     "legendFormat": "{{listener}}"
    }
   ]
  },
  {
   "title": "Client Versions",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_socket_server_metrics_connections{job=~\"kafka\",instance=~\"$instance\"}) by (clientSoftwareName, clientSoftwareVersion)",
     "legendFormat": "{{clientSoftwareName}} - {{clientSoftwareVersion}}"
    }
   ]
  }
 ]
}