{
 "title": "Streams Threads",
 "tags": [ "streams" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "measurement", "query": "commit, poll, process" },
   {
    "name": "job",
    "query": {
     "query": "kafka_streams_stream_thread_metrics_task_created_total"
    }
   },
   { "name": "instance", "label": "instance", "query": { "query": "application_streams" } },
   {
    "name": "thread",
    "label": "thread",
    "query": {
     "query": "kafka_streams_stream_thread_metrics_task_created_total{instance=~\"$instance\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "${measurement} total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(job,instance,thread) (kafka_streams_stream_thread_metrics_${measurement}_total{instance=~\"${instance}\", thread_id=~\"${thread}\", job=~\"${job}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_streams_stream_thread_metrics_${measurement}_total{thread_id=~\"${thread}\", instance=~\"${instance}\", job=~\"${job}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(job,instance,thread) (kafka_streams_stream_thread_metrics_${measurement}_rate{instance=~\"${instance}\", thread_id=~\"${thread}\", job=~\"${job}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kafka_streams_stream_thread_metrics_${measurement}_rate{thread_id=~\"${thread}\", instance=~\"${instance}\", job=~\"${job}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} rate (grafana computed)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(job,instance,thread) (rate(kafka_streams_stream_thread_metrics_${measurement}_total{thread_id=~\"${thread}\", instance=~\"${instance}\", job=~\"${job}\"}[1m]))",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} rate (grafana computed)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(kafka_streams_stream_thread_metrics_${measurement}_total{thread_id=~\"${thread}\", instance=~\"${instance}\", job=~\"${job}\"}[1m]))",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(job,instance,thread) (kafka_streams_stream_thread_metrics_${measurement}_ratio{instance=~\"${instance}\", thread_id=~\"${thread}\", job=~\"${job}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} ratio",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (kafka_streams_stream_thread_metrics_${measurement}_ratio{instance=~\"${instance}\", thread_id=~\"${thread}\", job=~\"${job}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(job,instance,thread) (kafka_streams_stream_thread_metrics_${measurement}_latency_avg{instance=~\"${instance}\", thread_id=~\"${thread}\", job=~\"${job}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} ratio",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (kafka_streams_stream_thread_metrics_${measurement}_latency_avg{instance=~\"${instance}\", thread_id=~\"${thread}\", job=~\"${job}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} records (avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(job,instance,thread) (kafka_streams_stream_thread_metrics_${measurement}_records_avg{instance=~\"${instance}\", thread_id=~\"${thread}\", job=~\"${job}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} records (avg)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (kafka_streams_stream_thread_metrics_${measurement}_records_avg{instance=~\"${instance}\", thread_id=~\"${thread}\", job=~\"${job}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  }
 ]
}